aspiretolearn/aspiretolearn/urls.py
from django.contrib import admin
from django.urls import include, path
# from allauth.socialaccount.providers.oauth2.views import OAuth2LoginView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include(('blogs.urls', 'blogs'))),
    path('accounts/', include('django.contrib.auth.urls')),
]

aspiretolearn/blogs/urls.py
from django.urls import path
from . import views

app_name = 'blogs'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('single-blog/<int:post_id>/',views.single_blog, name='single-blog'),
    path('single-blog/',views.single_blog, name='single-blog'),
    path('category/',views.category, name='category'),
    path('category/<int:cat_id>/',views.category, name='category'),
    path('contact/',views.contact, name='contact'),
    path('about/',views.about, name='about'),
    path('search_result/',views.search_result, name='search_result'),
    path('sign-up/', views.sign_up, name='sign_up'),
    path('log-in/', views.log_in, name='log_in'),
]

aspiretolearn/blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    category = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    status = models.BooleanField(default=True) 
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.category
    
class Tags(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    tags = models.CharField(max_length=200)
    status = models.BooleanField(default=True) 
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.category.category
    
class Post(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    content = models.TextField()
    status = models.BooleanField(default=True) 
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.title
    
class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.TextField()
    status = models.BooleanField(default=True) 
    date_created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.post.title

aspiretolearn/blogs/forms.py
# In your forms.py file
from django import forms
from .models import Post

class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={'class': 'form-control','cols':"30" ,'rows':"5"}))

class LogInForm(forms.Form):
    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'}))

class SignUpForm(forms.Form):
    username = forms.CharField(max_length=30, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Enter your email'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}))

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title']

aspiretolearn/blogs/views.py
from django.shortcuts import render
from .models import Post, Category, Comments
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from .forms import SignUpForm,CommentForm,LogInForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required


def log_in(request):
    if request.method == 'POST':
        form = LogInForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('blogs:home')
    else:
        form = LogInForm()
    return render(request, 'account/login.html', {'form': form})

@login_required
def home(request):
    post_obj = Post.objects.all()
    post_last = Post.objects.all()[:3]
    category_obj = Category.objects.all()
    return render(request,'blogs/home.html',{'post':post_obj,
                                             'category':category_obj,
                                             'post_last':post_last})

@login_required
def single_blog(request,post_id=None):
    if request.method == 'POST':
        Comments.objects.create(post_id=request.POST.get('post_id'),
                                author_id=request.user.id,
                                comment=request.POST.get('comment'))
    try:
        po_obj = Post.objects.get(id=post_id)
    except:
        po_obj = None
    post_last = Post.objects.all()[:4]
    form = CommentForm()
    comm = Comments.objects.filter(post_id=post_id)
    cat = Category.objects.all()
    all_list = []
    for i in cat:
        small_list = []
        small_list.append(i.id)
        small_list.append(i.category)
        small_list.append(len(list(Post.objects.filter(category_id=i.id))))
        all_list.append(small_list)
    return render(request,'blogs/single.html',{'po_obj':po_obj,
                                               'post_last':post_last,
                                               'form':form,
                                               'post_id':post_id,
                                               'comm':comm,
                                              'category_obj':all_list,})
@login_required
def category(request,cat_id=None):
    try:
        cat_obj = Category.objects.get(id=cat_id)
    except:
        cat_obj = None
    try:
        po_obj = Post.objects.filter(category_id=cat_id)
    except:
        po_obj = None
    all_list = []
    cat = Category.objects.all()
    for i in cat:
        small_list = []
        small_list.append(i.id)
        small_list.append(i.category)
        small_list.append(len(list(Post.objects.filter(category_id=i.id))))
        all_list.append(small_list)
    return render(request,'blogs/category.html',{'cat_obj':cat_obj,
                                                 'po_obj':po_obj,
                                                 'category_obj':all_list,})

@login_required
def about(request):
    return render(request,'blogs/about.html')

@login_required
def contact(request):
    return render(request,'blogs/contact.html')

@login_required
def search_result(request):
    print(request.GET.get('content'))
    try:
        matching_posts = Post.objects.filter(title__icontains=request.GET.get('content'))
    except:
        matching_posts = None
    print(matching_posts,'matching_posts')
    return render(request,'blogs/search-result.html', {'data': matching_posts,
                                                       'searched_item':request.GET.get('content')})

def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            if not (User.objects.filter(username=request.POST.get('username')) or User.objects.filter(email=request.POST.get('email'))):
                user = User.objects.create_user(username=request.POST.get('username'), password=request.POST.get('password'))
                user.email = request.POST.get('email')
                user.save()
                return redirect('blogs:home')
        return render(request, 'account/signup.html', {'form': form})
    else:
        form = SignUpForm()
    return render(request, 'account/signup.html', {'form': form})

aspiretolearn/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    {% include 'css.html' %}
<body>
    {% include 'header.html' %}
    {% block content %}{% endblock %}
	{% include 'footer.html' %}
    <!-- Preloader -->
    <div id="overlayer"></div>
    <div class="loader">
    	<div class="spinner-border text-primary" role="status">
    		<span class="visually-hidden">Loading...</span>
    	</div>
    </div>
    {% include 'js.html' %}
  </body>
  </html>

aspiretolearn/templates/blogs/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<div class="section search-result-wrap">
		<div class="container">
			<div class="row">
				<div class="col-12">
					<div class="heading">{{cat_obj.category}}</div>
				</div>
			</div>
			<div class="row posts-entry">
				<div class="col-lg-8">
					{% if po_obj %}
					{% for i in po_obj %}
					<div class="blog-entry d-flex blog-entry-search-item">
						<a href="{% url 'blogs:single-blog' i.id %}" class="img-link me-4">
							<img src="{% static 'images/img_1_sq.jpg' %}" alt="Image" class="img-fluid">
						</a>
						<div>
							<span class="date">{{i.date_created}}<a href="#">{{i.category.category}}</a></span>
							<h2><a href="{% url 'blogs:single-blog' i.id %}">{{i.title}}</a></h2>
							<p>{{i.content}}</p>
							<p><a href="{% url 'blogs:single-blog' i.id %}" class="btn btn-sm btn-outline-primary">Read More</a></p>
						</div>
					</div>
					{% endfor %}
					{% endif %}

					<div class="row text-start pt-5 border-top">
						<div class="col-md-12">
							<div class="custom-pagination">
								<span>1</span>
								<a href="#">2</a>
								<a href="#">3</a>
								<a href="#">4</a>
								<span>...</span>
								<a href="#">15</a>
							</div>
						</div>
					</div>

				</div>

				<div class="col-lg-4 sidebar">
					
					
					<!-- END sidebar-box -->
					<div class="sidebar-box">
						<h3 class="heading">Popular Posts</h3>
						<div class="post-entry-sidebar">
							<ul>
								<li>
									<a href="">
										<img src="{% static 'images/img_1_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
										<div class="text">
											<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
											<div class="post-meta">
												<span class="mr-2">March 15, 2018 </span>
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="">
										<img src="{% static 'images/img_2_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
										<div class="text">
											<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
											<div class="post-meta">
												<span class="mr-2">March 15, 2018 </span>
											</div>
										</div>
									</a>
								</li>
								<li>
									<a href="">
										<img src="{% static 'images/img_3_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
										<div class="text">
											<h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
											<div class="post-meta">
												<span class="mr-2">March 15, 2018 </span>
											</div>
										</div>
									</a>
								</li>
							</ul>
						</div>
					</div>
					<!-- END sidebar-box -->

					<div class="sidebar-box">
						<h3 class="heading">Categories</h3>
						<ul class="categories">
							{% if category_obj %}
							{% for i in category_obj %}
							<li><a href="{% url 'blogs:category' i.0 %}">{{i.1}}<span>{{i.2}}</span></a></li>
							{% endfor %}
							{% endif %}
						</ul>
					</div>
					<!-- END sidebar-box -->

					<div class="sidebar-box">
						<h3 class="heading">Tags</h3>
						<ul class="tags">
							<li><a href="#">Travel</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Business</a></li>
							<li><a href="#">Freelancing</a></li>
						</ul>
					</div>

				</div>
			</div>
		</div>
	</div>
{% endblock content %}

aspiretolearn/templates/blogs/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

	<section class="section bg-light">
		<div class="container">
			<div class="row align-items-stretch retro-layout">

				{% for i in post_last %}
				<div class="col-md-4">
					<a href="{% url 'blogs:single-blog' i.id %}" class="h-entry mb-30 v-height gradient">

						<div class="featured-img" style="background-image: url('/static/images/img_2_horizontal.jpg');"></div>

						<div class="text">
							<span class="date">{{i.date_created}}</span>
							<h2>{{i.title}}</h2>
						</div>
					</a>
				</div>
				{% endfor %}
			</div>
		</div>
	</section>
	<!-- End retroy layout blog posts -->
{% if category %}
{% for cat in category %}
	<section class="section">
		<div class="container">

			<div class="row mb-4">
				<div class="col-sm-6">
					<h2 class="posts-entry-title">{{cat.category}}</h2>
				</div>
				<div class="col-sm-6 text-sm-end"><a href="{% url 'blogs:category' cat.id %}" class="read-more">View All</a></div>
			</div>

			<div class="row">
				{% for po in post %}
				{% if po.category_id == cat.id %}
				
				<div class="col-lg-4 mb-4">
					<div class="post-entry-alt">
						<a href="{% url 'blogs:single-blog' po.id %}" class="img-link"><img src="{% static 'images/img_7_horizontal.jpg' %}" alt="Image" class="img-fluid"></a>
						<div class="excerpt">
							

							<h2><a href="{% url 'blogs:single-blog' po.id %}">{{po.title}}</a></h2>
							<div class="post-meta align-items-center text-left clearfix">
								<figure class="author-figure mb-0 me-3 float-start"><img src="{% static 'images/person_1.jpg' %}" alt="Image" class="img-fluid"></figure>
								<span class="d-inline-block mt-1">By <a href="{% url 'blogs:single-blog' po.id %}">{{po.author.username}}</a></span>
								<span>{{po.date_created}}</span>
							</div>

							<p>{{po.title}}</p>
							<p><a href="{% url 'blogs:single-blog' po.id %}" class="read-more">Continue Reading</a></p>
						</div>
					</div>
				</div>
				{% endif %}
				{% endfor %}
			</div>
			
		</div>
	</section>
{% endfor %}
{% endif %}

	{% endblock content %}

aspiretolearn/templates/blogs/single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


  <div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url('/static/images/hero_5.jpg');">
    <div class="container">
      <div class="row same-height justify-content-center">
        <div class="col-md-6">
          <div class="post-entry text-center">
            <h1 class="mb-4">{{po_obj.title}}</h1>
            <div class="post-meta align-items-center text-center">
              <figure class="author-figure mb-0 me-3 d-inline-block"><img src="{% static 'images/person_1.jpg' %}" alt="Image" class="img-fluid"></figure>
              <span class="d-inline-block mt-1">{{po_obj.author.username}}</span>
              <span>{{po_obj.date_created}}</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <section class="section">
    <div class="container">

      <div class="row blog-entries element-animate">

        <div class="col-md-12 col-lg-8 main-content">

          <div class="post-content-body">
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium nam quas inventore, ut iure iste modi eos adipisci ad ea itaque labore earum autem nobis et numquam, minima eius. Nam eius, non unde ut aut sunt eveniet rerum repellendus porro.</p>
            <p>Sint ab voluptates itaque, ipsum porro qui obcaecati cumque quas sit vel. Voluptatum provident id quis quo. Eveniet maiores perferendis officia veniam est laborum, expedita fuga doloribus natus repellendus dolorem ab similique sint eius cupiditate necessitatibus, magni nesciunt ex eos.</p>
            <p>Quis eius aspernatur, eaque culpa cumque reiciendis, nobis at earum assumenda similique ut? Aperiam vel aut, ex exercitationem eos consequuntur eaque culpa totam, deserunt, aspernatur quae eveniet hic provident ullam tempora error repudiandae sapiente illum rerum itaque voluptatem. Commodi, sequi.</p>
            <div class="row my-4">
              <div class="col-md-12 mb-4">
                <img src="{% static 'images/hero_1.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              </div>
              <div class="col-md-6 mb-4">
                <img src="{% static 'images/img_2_horizontal.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              </div>
              <div class="col-md-6 mb-4">
                <img src="{% static 'images/img_3_horizontal.jpg' %}" alt="Image placeholder" class="img-fluid rounded">
              </div>
            </div>
            <p>{{po_obj.content}}</p>
          </div>


          <div class="pt-5">
            <p>Categories:  <a href="#">Food</a>, <a href="#">Travel</a>  Tags: <a href="#">#manila</a>, <a href="#">#asia</a></p>
          </div>


          <div class="pt-5 comment-wrap">
            <h3 class="mb-5 heading">6 Comments</h3>
            <ul class="comment-list">
              {% for eachcomm in comm %}
              <li class="comment">
                <div class="vcard">
                  <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                </div>
                <div class="comment-body">
                  <h3>{{eachcomm.author.username}}</h3>
                  <div class="meta">{{eachcomm.date_created}}</div>
                  <p>{{eachcomm.comment}}</p>
                  <p><a href="#" class="reply rounded">Reply</a></p>
                </div>
              </li>

              {% endfor %}

                <ul class="children">
                  <li class="comment">
                    <div class="vcard">
                      <img src="{% static 'images/person_3.jpg' %}" alt="Image placeholder">
                    </div>
                    <div class="comment-body">
                      <h3>Jean Doe</h3>
                      <div class="meta">January 9, 2018 at 2:21pm</div>
                      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                      <p><a href="#" class="reply rounded">Reply</a></p>
                    </div>


                    <ul class="children">
                      <li class="comment">
                        <div class="vcard">
                          <img src="{% static 'images/person_4.jpg' %}" alt="Image placeholder">
                        </div>
                        <div class="comment-body">
                          <h3>Jean Doe</h3>
                          <div class="meta">January 9, 2018 at 2:21pm</div>
                          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                          <p><a href="#" class="reply rounded">Reply</a></p>
                        </div>

                        <ul class="children">
                          <li class="comment">
                            <div class="vcard">
                              <img src="{% static 'images/person_5.jpg' %}" alt="Image placeholder">
                            </div>
                            <div class="comment-body">
                              <h3>Jean Doe</h3>
                              <div class="meta">January 9, 2018 at 2:21pm</div>
                              <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                              <p><a href="#" class="reply rounded">Reply</a></p>
                            </div>
                          </li>
                        </ul>
                      </li>
                    </ul>
                  </li>
                </ul>
              </li>

              <li class="comment">
                <div class="vcard">
                  <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder">
                </div>
                <div class="comment-body">
                  <h3>Jean Doe</h3>
                  <div class="meta">January 9, 2018 at 2:21pm</div>
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur quidem laborum necessitatibus, ipsam impedit vitae autem, eum officia, fugiat saepe enim sapiente iste iure! Quam voluptas earum impedit necessitatibus, nihil?</p>
                  <p><a href="#" class="reply rounded">Reply</a></p>
                </div>
              </li>
            </ul>
            <!-- END comment-list -->

            <div class="comment-form-wrap pt-5">
              <h3 class="mb-5">Leave a comment</h3>
              <form action="{% url 'blogs:single-blog' post_id %}" method="post" class="p-5 bg-light">{% csrf_token %}
                <div class="form-group">
                  <input type="hidden" name="post_id" id="id_post" value="{{post_id}}" class="">
                  {{form}}
                </div>
                <div class="form-group">
                  <input type="submit" value="Post Comment" class="btn btn-primary">
                </div>

              </form>
            </div>
          </div>

        </div>

        <!-- END main-content -->

        <div class="col-md-12 col-lg-4 sidebar">
          
          <!-- END sidebar-box -->
          <div class="sidebar-box">
            <div class="bio text-center">
              <img src="{% static 'images/person_2.jpg' %}" alt="Image Placeholder" class="img-fluid mb-3">
              <div class="bio-body">
                <h2>Hannah Anderson</h2>
                <p class="mb-4">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Exercitationem facilis sunt repellendus excepturi beatae porro debitis voluptate nulla quo veniam fuga sit molestias minus.</p>
                <p><a href="#" class="btn btn-primary btn-sm rounded px-2 py-2">Read my bio</a></p>
                <p class="social">
                  <a href="#" class="p-2"><span class="fa fa-facebook"></span></a>
                  <a href="#" class="p-2"><span class="fa fa-twitter"></span></a>
                  <a href="#" class="p-2"><span class="fa fa-instagram"></span></a>
                  <a href="#" class="p-2"><span class="fa fa-youtube-play"></span></a>
                </p>
              </div>
            </div>
          </div>
          
          <div class="sidebar-box">
            <h3 class="heading">Popular Posts</h3>
            <div class="post-entry-sidebar">
              <ul>
                <li>
                  <a href="">
                    <img src="{% static 'images/img_1_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
                    <div class="text">
                      <h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
                      <div class="post-meta">
                        <span class="mr-2">March 15, 2018 </span>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="">
                    <img src="{% static 'images/img_2_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
                    <div class="text">
                      <h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
                      <div class="post-meta">
                        <span class="mr-2">March 15, 2018 </span>
                      </div>
                    </div>
                  </a>
                </li>
                <li>
                  <a href="">
                    <img src="{% static 'images/img_3_sq.jpg' %}" alt="Image placeholder" class="me-4 rounded">
                    <div class="text">
                      <h4>There’s a Cool New Way for Men to Wear Socks and Sandals</h4>
                      <div class="post-meta">
                        <span class="mr-2">March 15, 2018 </span>
                      </div>
                    </div>
                  </a>
                </li>
              </ul>
            </div>
          </div>

          <div class="sidebar-box">
            <h3 class="heading">Categories</h3>
            <ul class="categories">
              {% if category_obj %}
							{% for i in category_obj %}
							<li><a href="{% url 'blogs:category' i.0 %}">{{i.1}}<span>{{i.2}}</span></a></li>
							{% endfor %}
							{% endif %}
            </ul>
          </div>

          <div class="sidebar-box">
            <h3 class="heading">Tags</h3>
            <ul class="tags">
              <li><a href="#">Travel</a></li>
              <li><a href="#">Adventure</a></li>
              <li><a href="#">Food</a></li>
              <li><a href="#">Lifestyle</a></li>
              <li><a href="#">Business</a></li>
              <li><a href="#">Freelancing</a></li>
            </ul>
          </div>
        </div>
       

      </div>
    </div>
  </section>


  <section class="section posts-entry posts-entry-sm bg-light">
    <div class="container">
      <div class="row mb-4">
        <div class="col-12 text-uppercase text-black">More Blog Posts</div>
      </div>
      <div class="row">
        {% if post_last %}
        {% for i in post_last %}

        <div class="col-md-6 col-lg-3">
          <div class="blog-entry">
            <a href="#" class="img-link">
              <img src="{% static 'images/img_4_horizontal.jpg' %}" alt="Image" class="img-fluid">
            </a>
            <span class="date">{{i.date_created}}</span>
            <h2><a href="{% url 'blogs:single-blog' i.id %}">{{i.title}}</a></h2>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            <p><a href="{% url 'blogs:single-blog' i.id %}" class="read-more">Continue Reading</a></p>
          </div>
        </div>
        {% endfor %}
        {% endif %}
      </div>
    </div>
  </section>
{% endblock content %}

aspiretolearn/templates/header.html
{% load static %}

<div class="site-mobile-menu site-navbar-target">
    <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close">
            <span class="icofont-close js-menu-toggle"></span>
        </div>
    </div>
    <div class="site-mobile-menu-body"></div>
</div>

<nav class="site-nav">
    <div class="container">
        <div class="menu-bg-wrap">
            <div class="site-navigation">
                <div class="row g-0 align-items-center">
                    <div class="col-2">
                        <a href="{% url 'blogs:home' %}" class="logo m-0 float-start">AspireToLearn<span class="text-primary">.</span></a>
                    </div>
                    <div class="col-8 text-center">
                        <form action="#" class="search-form d-inline-block d-lg-none">
                            <input type="text" class="form-control" placeholder="Search...">
                            <span class="bi-search"></span>
                        </form>

                        <ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu mx-auto">
                            <li class="active"><a href="{% url 'blogs:home' %}">Home</a></li>
                            <li><a href="{% url 'blogs:category' %}">Category</a></li>
                            <li><a href="{% url 'blogs:about' %}">About</a></li>
                            <li><a href="{% url 'blogs:contact' %}">Contact</a></li>
                            {% if msg %}
                            <li>
                                <div class="post-meta align-items-center text-left clearfix">
                                    <a href="#">
                                        <figure class="author-figure mb-0 me-3 float-start">
                                            <img src="{% static 'images/person_1.jpg' %}" alt="Image" class="img-fluid">
                                        </figure>
                                        <span class="d-inline-block mt-1">{{msg}}
                                        
                                    </a></span>
                                    <a href="{% url 'logout' %}">Log Out</a>
                                </div>
                            </li>
                            {% else %}
                            <li class="has-children">
                                <a href="#">Account</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'blogs:log_in' %}">Log In</a></li>
                                    <li><a href="{% url 'blogs:sign_up' %}">Sign Up</a></li>
                                </ul>
                            </li>
                            {% endif %}
                            
                        </ul>
                    </div>
                    <div class="col-2 text-end">
                        <!-- <a href="#" class="burger ms-auto float-end site-menu-toggle js-menu-toggle d-inline-block d-lg-none light">
                            <span></span>
                        </a> -->
                        <form method='get' action="{% url 'blogs:search_result' %}" class="search-form d-none d-lg-inline-block"> {% csrf_token %}
                            <input type="text" id="id_content" name="content" class="form-control" placeholder="Search...">
                            <span class="bi-search"></span>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>

aspiretolearn/templates/js.html
{% load static %}
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'js/tiny-slider.js' %}"></script>
<script src="{% static 'js/flatpickr.min.js' %}"></script>
<script src="{% static 'js/aos.js' %}"></script>
<script src="{% static 'js/glightbox.min.js' %}"></script>
<script src="{% static 'js/navbar.js' %}"></script>
<script src="{% static 'js/counter.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>